### ISSUE TITLE
unable to use stringr translation on Snowflake

### ISSUE THREAD

**Issue by hershelm** [ndiquattro/flaky#1]
Hi there, thanks a lot for your helpful package and articles describing how to connect to Snowflake. I was able to successfully connect from RStudio, but am unable to use your custom SQL translation functions.

![image](https://user-images.githubusercontent.com/20047658/99037509-aaddf000-2538-11eb-9777-c3df9288666a.png)

**Comment by hershelm** [comment]
The first statement (item_id) works, but the second statement (item_id2) does not. Am I missing some setup step to take advantage of the other functions you've provided?

**Comment by hershelm** [comment]
here's a reprex of the issue mentioned above:

``` r
library(flaky)
library(dbplyr)

dbplyr::translate_sql(str_detect(x, y), con = dbplyr::simulate_dbi("Snowflake"))
#> Error: str_detect() is not available in this SQL variant
```

<sup>Created on 2020-11-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
sessionInfo()
#> R version 4.0.2 (2020-06-22)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 16.04.7 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/libblas/libblas.so.3.6.0
#> LAPACK: /usr/lib/lapack/liblapack.so.3.6.0
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] dbplyr_2.0.0     flaky_0.0.0.9000
#> 
#> loaded via a namespace (and not attached):
#>  [1] knitr_1.29       magrittr_1.5     tidyselect_1.1.0 R6_2.4.1        
#>  [5] rlang_0.4.7      stringr_1.4.0    highr_0.8        dplyr_1.0.1     
#>  [9] tools_4.0.2      xfun_0.16        DBI_1.1.0        htmltools_0.5.0 
#> [13] ellipsis_0.3.1   yaml_2.2.1       digest_0.6.25    assertthat_0.2.1
#> [17] tibble_3.0.3     lifecycle_0.2.0  crayon_1.3.4     purrr_0.3.4     
#> [21] vctrs_0.3.2      glue_1.4.1       evaluate_0.14    rmarkdown_2.3   
#> [25] stringi_1.4.6    compiler_4.0.2   pillar_1.4.6     generics_0.0.2  
#> [29] pkgconfig_2.0.3
```

</details>

**Comment by ndiquattro** [comment]
Hi @hershelm , unfortunately I've moved jobs and don't have access to Snowflake currently. But! I did have to deal with a similar issue recently. I think I've fixed the issue in the `dbplyr2` to branch. If you're able to check that it works I can merge it into master. 

You can install it with `remotes::install_github("ndiquattro/flaky@dbplyr2")`

**Comment by hershelm** [comment]
Hey @ndiquattro thanks for the reply! I get this error when trying to install

```
Installing package into ‘/home/hershel.mehta/R/x86_64-pc-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package ‘flaky’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘flaky’ in namespaceExport(ns, exports):
 undefined exports: sql_translate_env.Snowflake
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/hershel.mehta/R/x86_64-pc-linux-gnu-library/4.0/flaky’
* restoring previous ‘/home/hershel.mehta/R/x86_64-pc-linux-gnu-library/4.0/flaky’
Error: Failed to install 'flaky' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpFZcBES/file1723117d8023d/flaky_0.0.0.9000.tar.gz’ had non-zero exit status
```

It seems the NAMESPACE may need to be updated with the newly named `sql_translation.Snowflake`?

**Comment by ndiquattro** [comment]
Ok, tired to fix!

**Comment by hershelm** [comment]
I am able to install now without issue, but still get the following:

``` r
library(flaky)
library(dbplyr)

dbplyr::translate_sql(str_detect(x, y), con = dbplyr::simulate_dbi("Snowflake"))
#> Error: str_detect() is not available in this SQL variant
```

<sup>Created on 2020-11-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
sessionInfo()
#> R version 4.0.2 (2020-06-22)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 16.04.7 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/libblas/libblas.so.3.6.0
#> LAPACK: /usr/lib/lapack/liblapack.so.3.6.0
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] dbplyr_2.0.0     flaky_0.0.0.9000
#> 
#> loaded via a namespace (and not attached):
#>  [1] knitr_1.29       magrittr_1.5     tidyselect_1.1.0 R6_2.5.0        
#>  [5] rlang_0.4.8      stringr_1.4.0    highr_0.8        dplyr_1.0.2     
#>  [9] tools_4.0.2      xfun_0.16        DBI_1.1.0        htmltools_0.5.0 
#> [13] ellipsis_0.3.1   yaml_2.2.1       digest_0.6.27    assertthat_0.2.1
#> [17] tibble_3.0.4     lifecycle_0.2.0  crayon_1.3.4     purrr_0.3.4     
#> [21] vctrs_0.3.4      glue_1.4.2       evaluate_0.14    rmarkdown_2.3   
#> [25] stringi_1.4.6    compiler_4.0.2   pillar_1.4.6     generics_0.1.0  
#> [29] pkgconfig_2.0.3
```

</details>

**Comment by hershelm** [comment]
After installing from

```
remotes::install_github("ndiquattro/flaky@dbplyr2")
```

I am able to see the following

``` r
flaky::sql_translation.Snowflake()
#> <sql_variant>
#> scalar:    ^, <, <=, ==, >, >=, |, ||, -, :, !, !=, /, (, [, [[, {, $,
#> scalar:    *, &, &&, %>%, %/%, %%, +, abs, acos, as.character, as_date,
#> scalar:    as.Date, as_datetime, as.double, asin, as.integer,
#> scalar:    as.integer64, as.logical, as.numeric, as.POSIXct, atan,
#> scalar:    atan2, between, bitwAnd, bitwNot, bitwOr, bitwShiftL,
#> scalar:    bitwShiftR, bitwXor, c, case_when, ceil, ceiling, coalesce,
#> scalar:    cos, cosh, cot, coth, day, desc, exp, floor, hour, if,
#> scalar:    ifelse, if_else, %in%, is.na, is.null, log, log10, mday,
#> scalar:    minute, month, na_if, nchar, now, paste, paste0, pmax, pmin,
#> scalar:    qday, round, second, sign, sin, sinh, sql, sqrt, str_c,
#> scalar:    str_conv, str_count, str_detect, str_dup, str_ends,
#> scalar:    str_extract, str_extract_all, str_flatten, str_glue,
#> scalar:    str_glue_data, str_interp, str_length, str_locate,
#> scalar:    str_locate_all, str_match, str_match_all, str_order,
#> scalar:    str_pad, str_remove, str_remove_all, str_replace,
#> scalar:    str_replace_all, str_replace_na, str_sort, str_split,
#> scalar:    str_split_fixed, str_squish, str_starts, str_sub,
#> scalar:    str_subset, str_to_lower, str_to_title, str_to_upper,
#> scalar:    str_trim, str_trunc, str_view, str_view_all, str_which,
#> scalar:    str_wrap, substr, substring, switch, tan, tanh, today,
#> scalar:    tolower, toupper, trimws, wday, xor, yday, year
#> aggregate: cor, cov, cume_dist, cummax, cummean, cummin, cumsum,
#> aggregate: dense_rank, first, lag, last, lead, max, mean, median, min,
#> aggregate: min_rank, n, n_distinct, nth, ntile, order_by, paste,
#> aggregate: percent_rank, quantile, rank, row_number, sd, sum, var
#> window:    cor, cov, cume_dist, cummax, cummean, cummin, cumsum,
#> window:    dense_rank, first, lag, last, lead, max, mean, median, min,
#> window:    min_rank, n, n_distinct, nth, ntile, order_by, paste,
#> window:    percent_rank, quantile, rank, row_number, sd, sum, var
```

<sup>Created on 2020-11-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
sessionInfo()
#> R version 4.0.2 (2020-06-22)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 16.04.7 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/libblas/libblas.so.3.6.0
#> LAPACK: /usr/lib/lapack/liblapack.so.3.6.0
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] knitr_1.29       magrittr_1.5     tidyselect_1.1.0 R6_2.5.0        
#>  [5] rlang_0.4.8      stringr_1.4.0    highr_0.8        dplyr_1.0.2     
#>  [9] tools_4.0.2      xfun_0.16        DBI_1.1.0        dbplyr_2.0.0    
#> [13] htmltools_0.5.0  ellipsis_0.3.1   yaml_2.2.1       digest_0.6.27   
#> [17] assertthat_0.2.1 tibble_3.0.4     lifecycle_0.2.0  crayon_1.3.4    
#> [21] flaky_0.0.0.9000 purrr_0.3.4      vctrs_0.3.4      glue_1.4.2      
#> [25] evaluate_0.14    rmarkdown_2.3    stringi_1.4.6    compiler_4.0.2  
#> [29] pillar_1.4.6     generics_0.1.0   pkgconfig_2.0.3
```

</details>

**Comment by ndiquattro** [comment]
Closed in #3
